/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	v1v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonHTTPHealthCheck) DeepCopyInto(out *CommonHTTPHealthCheck) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.RequestPath != nil {
		in, out := &in.RequestPath, &out.RequestPath
		*out = new(string)
		**out = **in
	}
	if in.ProxyHeader != nil {
		in, out := &in.ProxyHeader, &out.ProxyHeader
		*out = new(ProxyHeaderType)
		**out = **in
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonHTTPHealthCheck.
func (in *CommonHTTPHealthCheck) DeepCopy() *CommonHTTPHealthCheck {
	if in == nil {
		return nil
	}
	out := new(CommonHTTPHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonHealthCheck) DeepCopyInto(out *CommonHealthCheck) {
	*out = *in
	if in.PortSpecification != nil {
		in, out := &in.PortSpecification, &out.PortSpecification
		*out = new(PortSpecificationType)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
	if in.PortName != nil {
		in, out := &in.PortName, &out.PortName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonHealthCheck.
func (in *CommonHealthCheck) DeepCopy() *CommonHealthCheck {
	if in == nil {
		return nil
	}
	out := new(CommonHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionDraining) DeepCopyInto(out *ConnectionDraining) {
	*out = *in
	if in.DrainingTimeoutSec != nil {
		in, out := &in.DrainingTimeoutSec, &out.DrainingTimeoutSec
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionDraining.
func (in *ConnectionDraining) DeepCopy() *ConnectionDraining {
	if in == nil {
		return nil
	}
	out := new(ConnectionDraining)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPBackendPolicy) DeepCopyInto(out *GCPBackendPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPBackendPolicy.
func (in *GCPBackendPolicy) DeepCopy() *GCPBackendPolicy {
	if in == nil {
		return nil
	}
	out := new(GCPBackendPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPBackendPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPBackendPolicyConfig) DeepCopyInto(out *GCPBackendPolicyConfig) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionAffinity != nil {
		in, out := &in.SessionAffinity, &out.SessionAffinity
		*out = new(SessionAffinityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionDraining != nil {
		in, out := &in.ConnectionDraining, &out.ConnectionDraining
		*out = new(ConnectionDraining)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeoutSec != nil {
		in, out := &in.TimeoutSec, &out.TimeoutSec
		*out = new(int64)
		**out = **in
	}
	if in.SecurityPolicy != nil {
		in, out := &in.SecurityPolicy, &out.SecurityPolicy
		*out = new(string)
		**out = **in
	}
	if in.IAP != nil {
		in, out := &in.IAP, &out.IAP
		*out = new(IdentityAwareProxyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPBackendPolicyConfig.
func (in *GCPBackendPolicyConfig) DeepCopy() *GCPBackendPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(GCPBackendPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPBackendPolicyList) DeepCopyInto(out *GCPBackendPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPBackendPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPBackendPolicyList.
func (in *GCPBackendPolicyList) DeepCopy() *GCPBackendPolicyList {
	if in == nil {
		return nil
	}
	out := new(GCPBackendPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPBackendPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPBackendPolicySpec) DeepCopyInto(out *GCPBackendPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(GCPBackendPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPBackendPolicySpec.
func (in *GCPBackendPolicySpec) DeepCopy() *GCPBackendPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GCPBackendPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPBackendPolicyStatus) DeepCopyInto(out *GCPBackendPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPBackendPolicyStatus.
func (in *GCPBackendPolicyStatus) DeepCopy() *GCPBackendPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GCPBackendPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPGatewayPolicy) DeepCopyInto(out *GCPGatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPGatewayPolicy.
func (in *GCPGatewayPolicy) DeepCopy() *GCPGatewayPolicy {
	if in == nil {
		return nil
	}
	out := new(GCPGatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPGatewayPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPGatewayPolicyConfig) DeepCopyInto(out *GCPGatewayPolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPGatewayPolicyConfig.
func (in *GCPGatewayPolicyConfig) DeepCopy() *GCPGatewayPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(GCPGatewayPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPGatewayPolicyList) DeepCopyInto(out *GCPGatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*GCPGatewayPolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GCPGatewayPolicy)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPGatewayPolicyList.
func (in *GCPGatewayPolicyList) DeepCopy() *GCPGatewayPolicyList {
	if in == nil {
		return nil
	}
	out := new(GCPGatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPGatewayPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPGatewayPolicySpec) DeepCopyInto(out *GCPGatewayPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(GCPGatewayPolicyConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPGatewayPolicySpec.
func (in *GCPGatewayPolicySpec) DeepCopy() *GCPGatewayPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GCPGatewayPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPGatewayPolicyStatus) DeepCopyInto(out *GCPGatewayPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPGatewayPolicyStatus.
func (in *GCPGatewayPolicyStatus) DeepCopy() *GCPGatewayPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GCPGatewayPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinityFilter) DeepCopyInto(out *GCPSessionAffinityFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinityFilter.
func (in *GCPSessionAffinityFilter) DeepCopy() *GCPSessionAffinityFilter {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinityFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPSessionAffinityFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinityFilterList) DeepCopyInto(out *GCPSessionAffinityFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPSessionAffinityFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinityFilterList.
func (in *GCPSessionAffinityFilterList) DeepCopy() *GCPSessionAffinityFilterList {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinityFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPSessionAffinityFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinityFilterStatus) DeepCopyInto(out *GCPSessionAffinityFilterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinityFilterStatus.
func (in *GCPSessionAffinityFilterStatus) DeepCopy() *GCPSessionAffinityFilterStatus {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinityFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinityPolicy) DeepCopyInto(out *GCPSessionAffinityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinityPolicy.
func (in *GCPSessionAffinityPolicy) DeepCopy() *GCPSessionAffinityPolicy {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPSessionAffinityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinityPolicyList) DeepCopyInto(out *GCPSessionAffinityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPSessionAffinityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinityPolicyList.
func (in *GCPSessionAffinityPolicyList) DeepCopy() *GCPSessionAffinityPolicyList {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPSessionAffinityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinityPolicySpec) DeepCopyInto(out *GCPSessionAffinityPolicySpec) {
	*out = *in
	in.GCPSessionAffinitySpec.DeepCopyInto(&out.GCPSessionAffinitySpec)
	in.TargetRef.DeepCopyInto(&out.TargetRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinityPolicySpec.
func (in *GCPSessionAffinityPolicySpec) DeepCopy() *GCPSessionAffinityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinityPolicyStatus) DeepCopyInto(out *GCPSessionAffinityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinityPolicyStatus.
func (in *GCPSessionAffinityPolicyStatus) DeepCopy() *GCPSessionAffinityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPSessionAffinitySpec) DeepCopyInto(out *GCPSessionAffinitySpec) {
	*out = *in
	if in.StatefulGeneratedCookie != nil {
		in, out := &in.StatefulGeneratedCookie, &out.StatefulGeneratedCookie
		*out = new(StatefulGeneratedCookieConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPSessionAffinitySpec.
func (in *GCPSessionAffinitySpec) DeepCopy() *GCPSessionAffinitySpec {
	if in == nil {
		return nil
	}
	out := new(GCPSessionAffinitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCHealthCheck) DeepCopyInto(out *GRPCHealthCheck) {
	*out = *in
	in.CommonHealthCheck.DeepCopyInto(&out.CommonHealthCheck)
	if in.GRPCServiceName != nil {
		in, out := &in.GRPCServiceName, &out.GRPCServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCHealthCheck.
func (in *GRPCHealthCheck) DeepCopy() *GRPCHealthCheck {
	if in == nil {
		return nil
	}
	out := new(GRPCHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTP2HealthCheck) DeepCopyInto(out *HTTP2HealthCheck) {
	*out = *in
	in.CommonHealthCheck.DeepCopyInto(&out.CommonHealthCheck)
	in.CommonHTTPHealthCheck.DeepCopyInto(&out.CommonHTTPHealthCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTP2HealthCheck.
func (in *HTTP2HealthCheck) DeepCopy() *HTTP2HealthCheck {
	if in == nil {
		return nil
	}
	out := new(HTTP2HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHealthCheck) DeepCopyInto(out *HTTPHealthCheck) {
	*out = *in
	in.CommonHealthCheck.DeepCopyInto(&out.CommonHealthCheck)
	in.CommonHTTPHealthCheck.DeepCopyInto(&out.CommonHTTPHealthCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHealthCheck.
func (in *HTTPHealthCheck) DeepCopy() *HTTPHealthCheck {
	if in == nil {
		return nil
	}
	out := new(HTTPHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSHealthCheck) DeepCopyInto(out *HTTPSHealthCheck) {
	*out = *in
	in.CommonHealthCheck.DeepCopyInto(&out.CommonHealthCheck)
	in.CommonHTTPHealthCheck.DeepCopyInto(&out.CommonHTTPHealthCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSHealthCheck.
func (in *HTTPSHealthCheck) DeepCopy() *HTTPSHealthCheck {
	if in == nil {
		return nil
	}
	out := new(HTTPSHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheck) DeepCopyInto(out *HealthCheck) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(TCPHealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPHealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(HTTPSHealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP2 != nil {
		in, out := &in.HTTP2, &out.HTTP2
		*out = new(HTTP2HealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPC != nil {
		in, out := &in.GRPC, &out.GRPC
		*out = new(GRPCHealthCheck)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheck.
func (in *HealthCheck) DeepCopy() *HealthCheck {
	if in == nil {
		return nil
	}
	out := new(HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckPolicy) DeepCopyInto(out *HealthCheckPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckPolicy.
func (in *HealthCheckPolicy) DeepCopy() *HealthCheckPolicy {
	if in == nil {
		return nil
	}
	out := new(HealthCheckPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthCheckPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckPolicyConfig) DeepCopyInto(out *HealthCheckPolicyConfig) {
	*out = *in
	if in.CheckIntervalSec != nil {
		in, out := &in.CheckIntervalSec, &out.CheckIntervalSec
		*out = new(int64)
		**out = **in
	}
	if in.TimeoutSec != nil {
		in, out := &in.TimeoutSec, &out.TimeoutSec
		*out = new(int64)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(int64)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(int64)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(HealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.LogConfig != nil {
		in, out := &in.LogConfig, &out.LogConfig
		*out = new(LogConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckPolicyConfig.
func (in *HealthCheckPolicyConfig) DeepCopy() *HealthCheckPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckPolicyList) DeepCopyInto(out *HealthCheckPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HealthCheckPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckPolicyList.
func (in *HealthCheckPolicyList) DeepCopy() *HealthCheckPolicyList {
	if in == nil {
		return nil
	}
	out := new(HealthCheckPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthCheckPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckPolicySpec) DeepCopyInto(out *HealthCheckPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(HealthCheckPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckPolicySpec.
func (in *HealthCheckPolicySpec) DeepCopy() *HealthCheckPolicySpec {
	if in == nil {
		return nil
	}
	out := new(HealthCheckPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckPolicyStatus) DeepCopyInto(out *HealthCheckPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckPolicyStatus.
func (in *HealthCheckPolicyStatus) DeepCopy() *HealthCheckPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(HealthCheckPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityAwareProxyConfig) DeepCopyInto(out *IdentityAwareProxyConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Oauth2ClientSecret != nil {
		in, out := &in.Oauth2ClientSecret, &out.Oauth2ClientSecret
		*out = new(Oauth2ClientSecret)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityAwareProxyConfig.
func (in *IdentityAwareProxyConfig) DeepCopy() *IdentityAwareProxyConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityAwareProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oauth2ClientSecret) DeepCopyInto(out *Oauth2ClientSecret) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oauth2ClientSecret.
func (in *Oauth2ClientSecret) DeepCopy() *Oauth2ClientSecret {
	if in == nil {
		return nil
	}
	out := new(Oauth2ClientSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionAffinityConfig) DeepCopyInto(out *SessionAffinityConfig) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.CookieTTLSec != nil {
		in, out := &in.CookieTTLSec, &out.CookieTTLSec
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionAffinityConfig.
func (in *SessionAffinityConfig) DeepCopy() *SessionAffinityConfig {
	if in == nil {
		return nil
	}
	out := new(SessionAffinityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulGeneratedCookieConfig) DeepCopyInto(out *StatefulGeneratedCookieConfig) {
	*out = *in
	if in.CookieTTLSeconds != nil {
		in, out := &in.CookieTTLSeconds, &out.CookieTTLSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulGeneratedCookieConfig.
func (in *StatefulGeneratedCookieConfig) DeepCopy() *StatefulGeneratedCookieConfig {
	if in == nil {
		return nil
	}
	out := new(StatefulGeneratedCookieConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPHealthCheck) DeepCopyInto(out *TCPHealthCheck) {
	*out = *in
	in.CommonHealthCheck.DeepCopyInto(&out.CommonHealthCheck)
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(string)
		**out = **in
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(string)
		**out = **in
	}
	if in.ProxyHeader != nil {
		in, out := &in.ProxyHeader, &out.ProxyHeader
		*out = new(ProxyHeaderType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPHealthCheck.
func (in *TCPHealthCheck) DeepCopy() *TCPHealthCheck {
	if in == nil {
		return nil
	}
	out := new(TCPHealthCheck)
	in.DeepCopyInto(out)
	return out
}
