/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/typed/networking/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGCPTrafficExtensions implements GCPTrafficExtensionInterface
type fakeGCPTrafficExtensions struct {
	*gentype.FakeClientWithList[*v1.GCPTrafficExtension, *v1.GCPTrafficExtensionList]
	Fake *FakeNetworkingV1
}

func newFakeGCPTrafficExtensions(fake *FakeNetworkingV1, namespace string) networkingv1.GCPTrafficExtensionInterface {
	return &fakeGCPTrafficExtensions{
		gentype.NewFakeClientWithList[*v1.GCPTrafficExtension, *v1.GCPTrafficExtensionList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("gcptrafficextensions"),
			v1.SchemeGroupVersion.WithKind("GCPTrafficExtension"),
			func() *v1.GCPTrafficExtension { return &v1.GCPTrafficExtension{} },
			func() *v1.GCPTrafficExtensionList { return &v1.GCPTrafficExtensionList{} },
			func(dst, src *v1.GCPTrafficExtensionList) { dst.ListMeta = src.ListMeta },
			func(list *v1.GCPTrafficExtensionList) []*v1.GCPTrafficExtension {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.GCPTrafficExtensionList, items []*v1.GCPTrafficExtension) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
