/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/typed/networking/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGCPServerTLSPolicies implements GCPServerTLSPolicyInterface
type fakeGCPServerTLSPolicies struct {
	*gentype.FakeClientWithList[*v1.GCPServerTLSPolicy, *v1.GCPServerTLSPolicyList]
	Fake *FakeNetworkingV1
}

func newFakeGCPServerTLSPolicies(fake *FakeNetworkingV1, namespace string) networkingv1.GCPServerTLSPolicyInterface {
	return &fakeGCPServerTLSPolicies{
		gentype.NewFakeClientWithList[*v1.GCPServerTLSPolicy, *v1.GCPServerTLSPolicyList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("gcpservertlspolicies"),
			v1.SchemeGroupVersion.WithKind("GCPServerTLSPolicy"),
			func() *v1.GCPServerTLSPolicy { return &v1.GCPServerTLSPolicy{} },
			func() *v1.GCPServerTLSPolicyList { return &v1.GCPServerTLSPolicyList{} },
			func(dst, src *v1.GCPServerTLSPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.GCPServerTLSPolicyList) []*v1.GCPServerTLSPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.GCPServerTLSPolicyList, items []*v1.GCPServerTLSPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
