/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/typed/networking/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGCPAuthzPolicies implements GCPAuthzPolicyInterface
type fakeGCPAuthzPolicies struct {
	*gentype.FakeClientWithList[*v1.GCPAuthzPolicy, *v1.GCPAuthzPolicyList]
	Fake *FakeNetworkingV1
}

func newFakeGCPAuthzPolicies(fake *FakeNetworkingV1, namespace string) networkingv1.GCPAuthzPolicyInterface {
	return &fakeGCPAuthzPolicies{
		gentype.NewFakeClientWithList[*v1.GCPAuthzPolicy, *v1.GCPAuthzPolicyList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("gcpauthzpolicies"),
			v1.SchemeGroupVersion.WithKind("GCPAuthzPolicy"),
			func() *v1.GCPAuthzPolicy { return &v1.GCPAuthzPolicy{} },
			func() *v1.GCPAuthzPolicyList { return &v1.GCPAuthzPolicyList{} },
			func(dst, src *v1.GCPAuthzPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.GCPAuthzPolicyList) []*v1.GCPAuthzPolicy { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.GCPAuthzPolicyList, items []*v1.GCPAuthzPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
