/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/typed/networking/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNetworkingV1 struct {
	*testing.Fake
}

func (c *FakeNetworkingV1) GCPAuthzPolicies(namespace string) v1.GCPAuthzPolicyInterface {
	return newFakeGCPAuthzPolicies(c, namespace)
}

func (c *FakeNetworkingV1) GCPBackendPolicies(namespace string) v1.GCPBackendPolicyInterface {
	return newFakeGCPBackendPolicies(c, namespace)
}

func (c *FakeNetworkingV1) GCPClientTLSPolicies(namespace string) v1.GCPClientTLSPolicyInterface {
	return newFakeGCPClientTLSPolicies(c, namespace)
}

func (c *FakeNetworkingV1) GCPGatewayPolicies(namespace string) v1.GCPGatewayPolicyInterface {
	return newFakeGCPGatewayPolicies(c, namespace)
}

func (c *FakeNetworkingV1) GCPServerTLSPolicies(namespace string) v1.GCPServerTLSPolicyInterface {
	return newFakeGCPServerTLSPolicies(c, namespace)
}

func (c *FakeNetworkingV1) GCPSessionAffinityFilters(namespace string) v1.GCPSessionAffinityFilterInterface {
	return newFakeGCPSessionAffinityFilters(c, namespace)
}

func (c *FakeNetworkingV1) GCPSessionAffinityPolicies(namespace string) v1.GCPSessionAffinityPolicyInterface {
	return newFakeGCPSessionAffinityPolicies(c, namespace)
}

func (c *FakeNetworkingV1) GCPTrafficDistributionPolicies(namespace string) v1.GCPTrafficDistributionPolicyInterface {
	return newFakeGCPTrafficDistributionPolicies(c, namespace)
}

func (c *FakeNetworkingV1) HealthCheckPolicies(namespace string) v1.HealthCheckPolicyInterface {
	return newFakeHealthCheckPolicies(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNetworkingV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
