/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGCPBackendPolicies implements GCPBackendPolicyInterface
type FakeGCPBackendPolicies struct {
	Fake *FakeNetworkingV1
	ns   string
}

var gcpbackendpoliciesResource = v1.SchemeGroupVersion.WithResource("gcpbackendpolicies")

var gcpbackendpoliciesKind = v1.SchemeGroupVersion.WithKind("GCPBackendPolicy")

// Get takes name of the gCPBackendPolicy, and returns the corresponding gCPBackendPolicy object, and an error if there is any.
func (c *FakeGCPBackendPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.GCPBackendPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gcpbackendpoliciesResource, c.ns, name), &v1.GCPBackendPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPBackendPolicy), err
}

// List takes label and field selectors, and returns the list of GCPBackendPolicies that match those selectors.
func (c *FakeGCPBackendPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.GCPBackendPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gcpbackendpoliciesResource, gcpbackendpoliciesKind, c.ns, opts), &v1.GCPBackendPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.GCPBackendPolicyList{ListMeta: obj.(*v1.GCPBackendPolicyList).ListMeta}
	for _, item := range obj.(*v1.GCPBackendPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gCPBackendPolicies.
func (c *FakeGCPBackendPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gcpbackendpoliciesResource, c.ns, opts))

}

// Create takes the representation of a gCPBackendPolicy and creates it.  Returns the server's representation of the gCPBackendPolicy, and an error, if there is any.
func (c *FakeGCPBackendPolicies) Create(ctx context.Context, gCPBackendPolicy *v1.GCPBackendPolicy, opts metav1.CreateOptions) (result *v1.GCPBackendPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gcpbackendpoliciesResource, c.ns, gCPBackendPolicy), &v1.GCPBackendPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPBackendPolicy), err
}

// Update takes the representation of a gCPBackendPolicy and updates it. Returns the server's representation of the gCPBackendPolicy, and an error, if there is any.
func (c *FakeGCPBackendPolicies) Update(ctx context.Context, gCPBackendPolicy *v1.GCPBackendPolicy, opts metav1.UpdateOptions) (result *v1.GCPBackendPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gcpbackendpoliciesResource, c.ns, gCPBackendPolicy), &v1.GCPBackendPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPBackendPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGCPBackendPolicies) UpdateStatus(ctx context.Context, gCPBackendPolicy *v1.GCPBackendPolicy, opts metav1.UpdateOptions) (*v1.GCPBackendPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gcpbackendpoliciesResource, "status", c.ns, gCPBackendPolicy), &v1.GCPBackendPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPBackendPolicy), err
}

// Delete takes name of the gCPBackendPolicy and deletes it. Returns an error if one occurs.
func (c *FakeGCPBackendPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gcpbackendpoliciesResource, c.ns, name, opts), &v1.GCPBackendPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGCPBackendPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gcpbackendpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.GCPBackendPolicyList{})
	return err
}

// Patch applies the patch and returns the patched gCPBackendPolicy.
func (c *FakeGCPBackendPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GCPBackendPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gcpbackendpoliciesResource, c.ns, name, pt, data, subresources...), &v1.GCPBackendPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPBackendPolicy), err
}
