/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

// GCPAuthzPolicyListerExpansion allows custom methods to be added to
// GCPAuthzPolicyLister.
type GCPAuthzPolicyListerExpansion interface{}

// GCPAuthzPolicyNamespaceListerExpansion allows custom methods to be added to
// GCPAuthzPolicyNamespaceLister.
type GCPAuthzPolicyNamespaceListerExpansion interface{}

// GCPBackendPolicyListerExpansion allows custom methods to be added to
// GCPBackendPolicyLister.
type GCPBackendPolicyListerExpansion interface{}

// GCPBackendPolicyNamespaceListerExpansion allows custom methods to be added to
// GCPBackendPolicyNamespaceLister.
type GCPBackendPolicyNamespaceListerExpansion interface{}

// GCPClientTLSPolicyListerExpansion allows custom methods to be added to
// GCPClientTLSPolicyLister.
type GCPClientTLSPolicyListerExpansion interface{}

// GCPClientTLSPolicyNamespaceListerExpansion allows custom methods to be added to
// GCPClientTLSPolicyNamespaceLister.
type GCPClientTLSPolicyNamespaceListerExpansion interface{}

// GCPGatewayPolicyListerExpansion allows custom methods to be added to
// GCPGatewayPolicyLister.
type GCPGatewayPolicyListerExpansion interface{}

// GCPGatewayPolicyNamespaceListerExpansion allows custom methods to be added to
// GCPGatewayPolicyNamespaceLister.
type GCPGatewayPolicyNamespaceListerExpansion interface{}

// GCPServerTLSPolicyListerExpansion allows custom methods to be added to
// GCPServerTLSPolicyLister.
type GCPServerTLSPolicyListerExpansion interface{}

// GCPServerTLSPolicyNamespaceListerExpansion allows custom methods to be added to
// GCPServerTLSPolicyNamespaceLister.
type GCPServerTLSPolicyNamespaceListerExpansion interface{}

// GCPSessionAffinityFilterListerExpansion allows custom methods to be added to
// GCPSessionAffinityFilterLister.
type GCPSessionAffinityFilterListerExpansion interface{}

// GCPSessionAffinityFilterNamespaceListerExpansion allows custom methods to be added to
// GCPSessionAffinityFilterNamespaceLister.
type GCPSessionAffinityFilterNamespaceListerExpansion interface{}

// GCPSessionAffinityPolicyListerExpansion allows custom methods to be added to
// GCPSessionAffinityPolicyLister.
type GCPSessionAffinityPolicyListerExpansion interface{}

// GCPSessionAffinityPolicyNamespaceListerExpansion allows custom methods to be added to
// GCPSessionAffinityPolicyNamespaceLister.
type GCPSessionAffinityPolicyNamespaceListerExpansion interface{}

// GCPTrafficDistributionPolicyListerExpansion allows custom methods to be added to
// GCPTrafficDistributionPolicyLister.
type GCPTrafficDistributionPolicyListerExpansion interface{}

// GCPTrafficDistributionPolicyNamespaceListerExpansion allows custom methods to be added to
// GCPTrafficDistributionPolicyNamespaceLister.
type GCPTrafficDistributionPolicyNamespaceListerExpansion interface{}

// HealthCheckPolicyListerExpansion allows custom methods to be added to
// HealthCheckPolicyLister.
type HealthCheckPolicyListerExpansion interface{}

// HealthCheckPolicyNamespaceListerExpansion allows custom methods to be added to
// HealthCheckPolicyNamespaceLister.
type HealthCheckPolicyNamespaceListerExpansion interface{}
