/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GCPAuthzPolicyLister helps list GCPAuthzPolicies.
// All objects returned here must be treated as read-only.
type GCPAuthzPolicyLister interface {
	// List lists all GCPAuthzPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPAuthzPolicy, err error)
	// GCPAuthzPolicies returns an object that can list and get GCPAuthzPolicies.
	GCPAuthzPolicies(namespace string) GCPAuthzPolicyNamespaceLister
	GCPAuthzPolicyListerExpansion
}

// gCPAuthzPolicyLister implements the GCPAuthzPolicyLister interface.
type gCPAuthzPolicyLister struct {
	listers.ResourceIndexer[*networkingv1.GCPAuthzPolicy]
}

// NewGCPAuthzPolicyLister returns a new GCPAuthzPolicyLister.
func NewGCPAuthzPolicyLister(indexer cache.Indexer) GCPAuthzPolicyLister {
	return &gCPAuthzPolicyLister{listers.New[*networkingv1.GCPAuthzPolicy](indexer, networkingv1.Resource("gcpauthzpolicy"))}
}

// GCPAuthzPolicies returns an object that can list and get GCPAuthzPolicies.
func (s *gCPAuthzPolicyLister) GCPAuthzPolicies(namespace string) GCPAuthzPolicyNamespaceLister {
	return gCPAuthzPolicyNamespaceLister{listers.NewNamespaced[*networkingv1.GCPAuthzPolicy](s.ResourceIndexer, namespace)}
}

// GCPAuthzPolicyNamespaceLister helps list and get GCPAuthzPolicies.
// All objects returned here must be treated as read-only.
type GCPAuthzPolicyNamespaceLister interface {
	// List lists all GCPAuthzPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPAuthzPolicy, err error)
	// Get retrieves the GCPAuthzPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1.GCPAuthzPolicy, error)
	GCPAuthzPolicyNamespaceListerExpansion
}

// gCPAuthzPolicyNamespaceLister implements the GCPAuthzPolicyNamespaceLister
// interface.
type gCPAuthzPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1.GCPAuthzPolicy]
}
