/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GCPClientTLSPolicyLister helps list GCPClientTLSPolicies.
// All objects returned here must be treated as read-only.
type GCPClientTLSPolicyLister interface {
	// List lists all GCPClientTLSPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPClientTLSPolicy, err error)
	// GCPClientTLSPolicies returns an object that can list and get GCPClientTLSPolicies.
	GCPClientTLSPolicies(namespace string) GCPClientTLSPolicyNamespaceLister
	GCPClientTLSPolicyListerExpansion
}

// gCPClientTLSPolicyLister implements the GCPClientTLSPolicyLister interface.
type gCPClientTLSPolicyLister struct {
	listers.ResourceIndexer[*networkingv1.GCPClientTLSPolicy]
}

// NewGCPClientTLSPolicyLister returns a new GCPClientTLSPolicyLister.
func NewGCPClientTLSPolicyLister(indexer cache.Indexer) GCPClientTLSPolicyLister {
	return &gCPClientTLSPolicyLister{listers.New[*networkingv1.GCPClientTLSPolicy](indexer, networkingv1.Resource("gcpclienttlspolicy"))}
}

// GCPClientTLSPolicies returns an object that can list and get GCPClientTLSPolicies.
func (s *gCPClientTLSPolicyLister) GCPClientTLSPolicies(namespace string) GCPClientTLSPolicyNamespaceLister {
	return gCPClientTLSPolicyNamespaceLister{listers.NewNamespaced[*networkingv1.GCPClientTLSPolicy](s.ResourceIndexer, namespace)}
}

// GCPClientTLSPolicyNamespaceLister helps list and get GCPClientTLSPolicies.
// All objects returned here must be treated as read-only.
type GCPClientTLSPolicyNamespaceLister interface {
	// List lists all GCPClientTLSPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPClientTLSPolicy, err error)
	// Get retrieves the GCPClientTLSPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1.GCPClientTLSPolicy, error)
	GCPClientTLSPolicyNamespaceListerExpansion
}

// gCPClientTLSPolicyNamespaceLister implements the GCPClientTLSPolicyNamespaceLister
// interface.
type gCPClientTLSPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1.GCPClientTLSPolicy]
}
