/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GCPGatewayPolicyLister helps list GCPGatewayPolicies.
// All objects returned here must be treated as read-only.
type GCPGatewayPolicyLister interface {
	// List lists all GCPGatewayPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.GCPGatewayPolicy, err error)
	// GCPGatewayPolicies returns an object that can list and get GCPGatewayPolicies.
	GCPGatewayPolicies(namespace string) GCPGatewayPolicyNamespaceLister
	GCPGatewayPolicyListerExpansion
}

// gCPGatewayPolicyLister implements the GCPGatewayPolicyLister interface.
type gCPGatewayPolicyLister struct {
	indexer cache.Indexer
}

// NewGCPGatewayPolicyLister returns a new GCPGatewayPolicyLister.
func NewGCPGatewayPolicyLister(indexer cache.Indexer) GCPGatewayPolicyLister {
	return &gCPGatewayPolicyLister{indexer: indexer}
}

// List lists all GCPGatewayPolicies in the indexer.
func (s *gCPGatewayPolicyLister) List(selector labels.Selector) (ret []*v1.GCPGatewayPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.GCPGatewayPolicy))
	})
	return ret, err
}

// GCPGatewayPolicies returns an object that can list and get GCPGatewayPolicies.
func (s *gCPGatewayPolicyLister) GCPGatewayPolicies(namespace string) GCPGatewayPolicyNamespaceLister {
	return gCPGatewayPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GCPGatewayPolicyNamespaceLister helps list and get GCPGatewayPolicies.
// All objects returned here must be treated as read-only.
type GCPGatewayPolicyNamespaceLister interface {
	// List lists all GCPGatewayPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.GCPGatewayPolicy, err error)
	// Get retrieves the GCPGatewayPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.GCPGatewayPolicy, error)
	GCPGatewayPolicyNamespaceListerExpansion
}

// gCPGatewayPolicyNamespaceLister implements the GCPGatewayPolicyNamespaceLister
// interface.
type gCPGatewayPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GCPGatewayPolicies in the indexer for a given namespace.
func (s gCPGatewayPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1.GCPGatewayPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.GCPGatewayPolicy))
	})
	return ret, err
}

// Get retrieves the GCPGatewayPolicy from the indexer for a given namespace and name.
func (s gCPGatewayPolicyNamespaceLister) Get(name string) (*v1.GCPGatewayPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("gcpgatewaypolicy"), name)
	}
	return obj.(*v1.GCPGatewayPolicy), nil
}
