/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GCPServerTLSPolicyLister helps list GCPServerTLSPolicies.
// All objects returned here must be treated as read-only.
type GCPServerTLSPolicyLister interface {
	// List lists all GCPServerTLSPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPServerTLSPolicy, err error)
	// GCPServerTLSPolicies returns an object that can list and get GCPServerTLSPolicies.
	GCPServerTLSPolicies(namespace string) GCPServerTLSPolicyNamespaceLister
	GCPServerTLSPolicyListerExpansion
}

// gCPServerTLSPolicyLister implements the GCPServerTLSPolicyLister interface.
type gCPServerTLSPolicyLister struct {
	listers.ResourceIndexer[*networkingv1.GCPServerTLSPolicy]
}

// NewGCPServerTLSPolicyLister returns a new GCPServerTLSPolicyLister.
func NewGCPServerTLSPolicyLister(indexer cache.Indexer) GCPServerTLSPolicyLister {
	return &gCPServerTLSPolicyLister{listers.New[*networkingv1.GCPServerTLSPolicy](indexer, networkingv1.Resource("gcpservertlspolicy"))}
}

// GCPServerTLSPolicies returns an object that can list and get GCPServerTLSPolicies.
func (s *gCPServerTLSPolicyLister) GCPServerTLSPolicies(namespace string) GCPServerTLSPolicyNamespaceLister {
	return gCPServerTLSPolicyNamespaceLister{listers.NewNamespaced[*networkingv1.GCPServerTLSPolicy](s.ResourceIndexer, namespace)}
}

// GCPServerTLSPolicyNamespaceLister helps list and get GCPServerTLSPolicies.
// All objects returned here must be treated as read-only.
type GCPServerTLSPolicyNamespaceLister interface {
	// List lists all GCPServerTLSPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPServerTLSPolicy, err error)
	// Get retrieves the GCPServerTLSPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1.GCPServerTLSPolicy, error)
	GCPServerTLSPolicyNamespaceListerExpansion
}

// gCPServerTLSPolicyNamespaceLister implements the GCPServerTLSPolicyNamespaceLister
// interface.
type gCPServerTLSPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1.GCPServerTLSPolicy]
}
