/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GCPTrafficExtensionLister helps list GCPTrafficExtensions.
// All objects returned here must be treated as read-only.
type GCPTrafficExtensionLister interface {
	// List lists all GCPTrafficExtensions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPTrafficExtension, err error)
	// GCPTrafficExtensions returns an object that can list and get GCPTrafficExtensions.
	GCPTrafficExtensions(namespace string) GCPTrafficExtensionNamespaceLister
	GCPTrafficExtensionListerExpansion
}

// gCPTrafficExtensionLister implements the GCPTrafficExtensionLister interface.
type gCPTrafficExtensionLister struct {
	listers.ResourceIndexer[*networkingv1.GCPTrafficExtension]
}

// NewGCPTrafficExtensionLister returns a new GCPTrafficExtensionLister.
func NewGCPTrafficExtensionLister(indexer cache.Indexer) GCPTrafficExtensionLister {
	return &gCPTrafficExtensionLister{listers.New[*networkingv1.GCPTrafficExtension](indexer, networkingv1.Resource("gcptrafficextension"))}
}

// GCPTrafficExtensions returns an object that can list and get GCPTrafficExtensions.
func (s *gCPTrafficExtensionLister) GCPTrafficExtensions(namespace string) GCPTrafficExtensionNamespaceLister {
	return gCPTrafficExtensionNamespaceLister{listers.NewNamespaced[*networkingv1.GCPTrafficExtension](s.ResourceIndexer, namespace)}
}

// GCPTrafficExtensionNamespaceLister helps list and get GCPTrafficExtensions.
// All objects returned here must be treated as read-only.
type GCPTrafficExtensionNamespaceLister interface {
	// List lists all GCPTrafficExtensions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPTrafficExtension, err error)
	// Get retrieves the GCPTrafficExtension from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1.GCPTrafficExtension, error)
	GCPTrafficExtensionNamespaceListerExpansion
}

// gCPTrafficExtensionNamespaceLister implements the GCPTrafficExtensionNamespaceLister
// interface.
type gCPTrafficExtensionNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1.GCPTrafficExtension]
}
