/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GCPTrafficDistributionPolicyLister helps list GCPTrafficDistributionPolicies.
// All objects returned here must be treated as read-only.
type GCPTrafficDistributionPolicyLister interface {
	// List lists all GCPTrafficDistributionPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPTrafficDistributionPolicy, err error)
	// GCPTrafficDistributionPolicies returns an object that can list and get GCPTrafficDistributionPolicies.
	GCPTrafficDistributionPolicies(namespace string) GCPTrafficDistributionPolicyNamespaceLister
	GCPTrafficDistributionPolicyListerExpansion
}

// gCPTrafficDistributionPolicyLister implements the GCPTrafficDistributionPolicyLister interface.
type gCPTrafficDistributionPolicyLister struct {
	listers.ResourceIndexer[*networkingv1.GCPTrafficDistributionPolicy]
}

// NewGCPTrafficDistributionPolicyLister returns a new GCPTrafficDistributionPolicyLister.
func NewGCPTrafficDistributionPolicyLister(indexer cache.Indexer) GCPTrafficDistributionPolicyLister {
	return &gCPTrafficDistributionPolicyLister{listers.New[*networkingv1.GCPTrafficDistributionPolicy](indexer, networkingv1.Resource("gcptrafficdistributionpolicy"))}
}

// GCPTrafficDistributionPolicies returns an object that can list and get GCPTrafficDistributionPolicies.
func (s *gCPTrafficDistributionPolicyLister) GCPTrafficDistributionPolicies(namespace string) GCPTrafficDistributionPolicyNamespaceLister {
	return gCPTrafficDistributionPolicyNamespaceLister{listers.NewNamespaced[*networkingv1.GCPTrafficDistributionPolicy](s.ResourceIndexer, namespace)}
}

// GCPTrafficDistributionPolicyNamespaceLister helps list and get GCPTrafficDistributionPolicies.
// All objects returned here must be treated as read-only.
type GCPTrafficDistributionPolicyNamespaceLister interface {
	// List lists all GCPTrafficDistributionPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.GCPTrafficDistributionPolicy, err error)
	// Get retrieves the GCPTrafficDistributionPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1.GCPTrafficDistributionPolicy, error)
	GCPTrafficDistributionPolicyNamespaceListerExpansion
}

// gCPTrafficDistributionPolicyNamespaceLister implements the GCPTrafficDistributionPolicyNamespaceLister
// interface.
type gCPTrafficDistributionPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1.GCPTrafficDistributionPolicy]
}
