/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	scheme "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GCPSessionAffinityFiltersGetter has a method to return a GCPSessionAffinityFilterInterface.
// A group's client should implement this interface.
type GCPSessionAffinityFiltersGetter interface {
	GCPSessionAffinityFilters(namespace string) GCPSessionAffinityFilterInterface
}

// GCPSessionAffinityFilterInterface has methods to work with GCPSessionAffinityFilter resources.
type GCPSessionAffinityFilterInterface interface {
	Create(ctx context.Context, gCPSessionAffinityFilter *v1.GCPSessionAffinityFilter, opts metav1.CreateOptions) (*v1.GCPSessionAffinityFilter, error)
	Update(ctx context.Context, gCPSessionAffinityFilter *v1.GCPSessionAffinityFilter, opts metav1.UpdateOptions) (*v1.GCPSessionAffinityFilter, error)
	UpdateStatus(ctx context.Context, gCPSessionAffinityFilter *v1.GCPSessionAffinityFilter, opts metav1.UpdateOptions) (*v1.GCPSessionAffinityFilter, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.GCPSessionAffinityFilter, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.GCPSessionAffinityFilterList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GCPSessionAffinityFilter, err error)
	GCPSessionAffinityFilterExpansion
}

// gCPSessionAffinityFilters implements GCPSessionAffinityFilterInterface
type gCPSessionAffinityFilters struct {
	client rest.Interface
	ns     string
}

// newGCPSessionAffinityFilters returns a GCPSessionAffinityFilters
func newGCPSessionAffinityFilters(c *NetworkingV1Client, namespace string) *gCPSessionAffinityFilters {
	return &gCPSessionAffinityFilters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gCPSessionAffinityFilter, and returns the corresponding gCPSessionAffinityFilter object, and an error if there is any.
func (c *gCPSessionAffinityFilters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.GCPSessionAffinityFilter, err error) {
	result = &v1.GCPSessionAffinityFilter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GCPSessionAffinityFilters that match those selectors.
func (c *gCPSessionAffinityFilters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.GCPSessionAffinityFilterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.GCPSessionAffinityFilterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gCPSessionAffinityFilters.
func (c *gCPSessionAffinityFilters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gCPSessionAffinityFilter and creates it.  Returns the server's representation of the gCPSessionAffinityFilter, and an error, if there is any.
func (c *gCPSessionAffinityFilters) Create(ctx context.Context, gCPSessionAffinityFilter *v1.GCPSessionAffinityFilter, opts metav1.CreateOptions) (result *v1.GCPSessionAffinityFilter, err error) {
	result = &v1.GCPSessionAffinityFilter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gCPSessionAffinityFilter).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gCPSessionAffinityFilter and updates it. Returns the server's representation of the gCPSessionAffinityFilter, and an error, if there is any.
func (c *gCPSessionAffinityFilters) Update(ctx context.Context, gCPSessionAffinityFilter *v1.GCPSessionAffinityFilter, opts metav1.UpdateOptions) (result *v1.GCPSessionAffinityFilter, err error) {
	result = &v1.GCPSessionAffinityFilter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		Name(gCPSessionAffinityFilter.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gCPSessionAffinityFilter).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *gCPSessionAffinityFilters) UpdateStatus(ctx context.Context, gCPSessionAffinityFilter *v1.GCPSessionAffinityFilter, opts metav1.UpdateOptions) (result *v1.GCPSessionAffinityFilter, err error) {
	result = &v1.GCPSessionAffinityFilter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		Name(gCPSessionAffinityFilter.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gCPSessionAffinityFilter).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gCPSessionAffinityFilter and deletes it. Returns an error if one occurs.
func (c *gCPSessionAffinityFilters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gCPSessionAffinityFilters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gCPSessionAffinityFilter.
func (c *gCPSessionAffinityFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GCPSessionAffinityFilter, err error) {
	result = &v1.GCPSessionAffinityFilter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gcpsessionaffinityfilters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
