/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	scheme "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GCPServerTLSPoliciesGetter has a method to return a GCPServerTLSPolicyInterface.
// A group's client should implement this interface.
type GCPServerTLSPoliciesGetter interface {
	GCPServerTLSPolicies(namespace string) GCPServerTLSPolicyInterface
}

// GCPServerTLSPolicyInterface has methods to work with GCPServerTLSPolicy resources.
type GCPServerTLSPolicyInterface interface {
	Create(ctx context.Context, gCPServerTLSPolicy *networkingv1.GCPServerTLSPolicy, opts metav1.CreateOptions) (*networkingv1.GCPServerTLSPolicy, error)
	Update(ctx context.Context, gCPServerTLSPolicy *networkingv1.GCPServerTLSPolicy, opts metav1.UpdateOptions) (*networkingv1.GCPServerTLSPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gCPServerTLSPolicy *networkingv1.GCPServerTLSPolicy, opts metav1.UpdateOptions) (*networkingv1.GCPServerTLSPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*networkingv1.GCPServerTLSPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*networkingv1.GCPServerTLSPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *networkingv1.GCPServerTLSPolicy, err error)
	GCPServerTLSPolicyExpansion
}

// gCPServerTLSPolicies implements GCPServerTLSPolicyInterface
type gCPServerTLSPolicies struct {
	*gentype.ClientWithList[*networkingv1.GCPServerTLSPolicy, *networkingv1.GCPServerTLSPolicyList]
}

// newGCPServerTLSPolicies returns a GCPServerTLSPolicies
func newGCPServerTLSPolicies(c *NetworkingV1Client, namespace string) *gCPServerTLSPolicies {
	return &gCPServerTLSPolicies{
		gentype.NewClientWithList[*networkingv1.GCPServerTLSPolicy, *networkingv1.GCPServerTLSPolicyList](
			"gcpservertlspolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *networkingv1.GCPServerTLSPolicy { return &networkingv1.GCPServerTLSPolicy{} },
			func() *networkingv1.GCPServerTLSPolicyList { return &networkingv1.GCPServerTLSPolicyList{} },
		),
	}
}
