/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	versioned "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned"
	internalinterfaces "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/listers/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GCPSessionAffinityPolicyInformer provides access to a shared informer and lister for
// GCPSessionAffinityPolicies.
type GCPSessionAffinityPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.GCPSessionAffinityPolicyLister
}

type gCPSessionAffinityPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGCPSessionAffinityPolicyInformer constructs a new informer for GCPSessionAffinityPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGCPSessionAffinityPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGCPSessionAffinityPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGCPSessionAffinityPolicyInformer constructs a new informer for GCPSessionAffinityPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGCPSessionAffinityPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1().GCPSessionAffinityPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1().GCPSessionAffinityPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&networkingv1.GCPSessionAffinityPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *gCPSessionAffinityPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGCPSessionAffinityPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gCPSessionAffinityPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&networkingv1.GCPSessionAffinityPolicy{}, f.defaultInformer)
}

func (f *gCPSessionAffinityPolicyInformer) Lister() v1.GCPSessionAffinityPolicyLister {
	return v1.NewGCPSessionAffinityPolicyLister(f.Informer().GetIndexer())
}
